version: '1'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=restaurant'
      - 'POSTGRES_PASSWORD=1234'